blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.needle.tools
    about: Ask questions and discuss with other Needle Engine users in real time.
  - name: Questions & Discussions
    url: https://github.com/needle-tools/needle-engine-support/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
