name: discord message
on:
  issues:
    types: [opened]
jobs:
  newissue:
    if: contains(github.event.comment.html_url, 'comment') == false
    name: Discord New Issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        username: "${{github.event.issue.user.login}}"
        avatar_url : "${{github.event.issue.user.avatar_url}}"
        message: "**New issue** → ${{github.event.issue.title}}\n<${{github.event.issue.html_url}}>"
